//! `.claude-plugin/plugin.json` と `hooks/hooks.json` を NAME と rules 行から生成する。
//!
//! manifest を手書きしないのは、名前の字面が repo へ散るのを避けるためである
//! （器 SPEC §7）。生成は冪等で、同じ workspace からは同じ bytes が出る。
//! hook の timeout は数値を焼かず rules 行 `hook.timeout_s` から読む（憲法 C1 / C5）。

use crate::check::Layout;
use crate::toml_lite;
use std::fs;
use std::path::Path;

/// plugin manifest の相対 path。
pub const MANIFEST_REL: &str = ".claude-plugin/plugin.json";

/// hook manifest の相対 path。
pub const HOOKS_REL: &str = "hooks/hooks.json";

/// marketplace manifest の相対 path。
pub const MARKETPLACE_REL: &str = ".claude-plugin/marketplace.json";

/// 規則の値の正本の相対 path。
pub const RULES_REL: &str = "rules/manifest.toml";

/// hook 1 回の timeout（秒）を持つ rules 行。
pub const ROW_TIMEOUT: &str = "hook.timeout_s";

/// `PreToolUse` で見る tool の matcher。
const MATCHER: &str = "Edit|Write|MultiEdit|NotebookEdit";

/// `SessionStart` に紐づく subcommand。
const SUB_SESSION_START: &str = "session-start";

/// `PreToolUse` に紐づく subcommand。
const SUB_PRE_TOOL_USE: &str = "pre-tool-use";

/// `PermissionRequest` で見る tool の matcher（**`Bash` だけ**）。
///
/// 内蔵 guard の問いに答えるのは `Bash` の周に限る。広げると器が答える筋合いの無い
/// 承認まで機械が deny することになる。
const MATCHER_PERMISSION: &str = "Bash";

/// `PermissionRequest` に紐づく subcommand。
const SUB_PERMISSION_REQUEST: &str = "permission-request";

/// plugin の説明文。**2 つの manifest が同じ 1 箇所から出す**（写して持つと片方だけ動く）。
fn description(name: &str) -> String {
    format!("{name} plugin manifest (generated by cargo xtask gen-manifest)")
}

/// `name` / `version` / `description` の 3 key を持つ manifest 本文を組み立てる。
pub fn render(name: &str, version: &str) -> String {
    let description = description(name);
    format!("{{\n  \"name\": \"{name}\",\n  \"version\": \"{version}\",\n  \"description\": \"{description}\"\n}}\n")
}

/// `name` / `description` / `owner` / `plugins` の 4 key を持つ marketplace 本文を組み立てる。
///
/// **個人の handle・repo の URL・host の path・口座名を 1 文字も持たない**（本 repo は
/// PUBLIC・SRS CON2）。`owner.url` は任意の field なので**置かない**——置けるものを置くと、
/// 生成器が個人情報を repo へ流し込む常設の口になる。`source` を `./` に取るのは、この repo
/// 自身を directory marketplace として読ませるためで、絶対 path を書かずに済む形でもある。
/// marketplace 自身の `description` は `claude plugin validate` が見る key で、plugins 側と
/// 同じ共有 [`description`] から出す（`author` は個人情報になりうるので足さない・A1）。
pub fn render_marketplace(name: &str) -> String {
    let description = description(name);
    format!(
        "{{\n  \"name\": \"{name}\",\n  \"description\": \"{description}\",\n  \"owner\": {{\n    \"name\": \"{name}\"\n  }},\n  \"plugins\": [\n    {{\n      \"name\": \"{name}\",\n      \"source\": \"./\",\n      \"description\": \"{description}\"\n    }}\n  ]\n}}\n"
    )
}

/// hook が起動するコマンドの字面。
///
/// `${<NAME_UPPER>_BIN:-<NAME>}` の展開は **Claude Code が hook を起動する shell**
/// が行う。器そのものは env を 1 つも読まない（憲法 C2.2・ADR-0004 §2.4）。
fn command(name: &str, sub: &str) -> String {
    format!("\\\"${{{}_BIN:-{name}}}\\\" hook {sub}", name.to_uppercase())
}

/// 1 event 分の entry を組む。
fn entry(event: &str, matcher: Option<&str>, name: &str, sub: &str, timeout: u64) -> String {
    let head = match matcher {
        Some(found) => format!("        \"matcher\": \"{found}\",\n"),
        None => String::new(),
    };
    format!(
        "    \"{event}\": [\n      {{\n{head}        \"hooks\": [\n          {{\n            \"type\": \"command\",\n            \"command\": \"{}\",\n            \"timeout\": {timeout}\n          }}\n        ]\n      }}\n    ]",
        command(name, sub)
    )
}

/// hooks.json 本文を組み立てる（entry は 3 つ・timeout は rules 行を写す）。
pub fn render_hooks(name: &str, timeout: u64) -> String {
    let entries = [
        entry("SessionStart", None, name, SUB_SESSION_START, timeout),
        entry("PreToolUse", Some(MATCHER), name, SUB_PRE_TOOL_USE, timeout),
        entry(
            "PermissionRequest",
            Some(MATCHER_PERMISSION),
            name,
            SUB_PERMISSION_REQUEST,
            timeout,
        ),
    ];
    format!("{{\n  \"hooks\": {{\n{}\n  }}\n}}\n", entries.join(",\n"))
}

/// rules manifest から `id` の行の `value` を整数で引く。
///
/// `[[rule]]` は array-of-tables なので、section 行で block を切り替えながら
/// 「いま読んでいる block の id」を追う（file 全体の行 grep はしない）。
pub fn rule_int(text: &str, id: &str) -> Result<u64, String> {
    let mut current: Option<String> = None;
    for line in text.lines() {
        if toml_lite::section_header(line).is_some() {
            current = None;
            continue;
        }
        let Some((key, raw)) = toml_lite::key_value(line) else {
            continue;
        };
        if key == "id" {
            current = toml_lite::quoted(raw);
        }
        if key == "value" && current.as_deref() == Some(id) {
            return raw
                .parse::<u64>()
                .map_err(|err| format!("{id} の value が整数でない（{raw}・{err}）"));
        }
    }
    Err(format!("{id} が {RULES_REL} に無い"))
}

/// `root` 配下の 1 file を親 dir ごと書き出す。
fn write_under(root: &Path, rel: &str, body: &str) -> Result<String, String> {
    let path = root.join(rel);
    let dir = path
        .parent()
        .ok_or_else(|| format!("{} の親 dir が無い", path.display()))?;
    fs::create_dir_all(dir).map_err(|err| format!("{} を作れない: {err}", dir.display()))?;
    fs::write(&path, body).map_err(|err| format!("{} を書けない: {err}", path.display()))?;
    Ok(path.display().to_string())
}

/// workspace `root` の plugin manifest と hook manifest を生成して書き出し、報告行を返す。
pub fn generate(root: &Path) -> Result<String, String> {
    let layout = Layout::discover(root)?;
    let version = layout.core_version()?;
    let rules = fs::read_to_string(root.join(RULES_REL))
        .map_err(|err| format!("{RULES_REL} を読めない: {err}"))?;
    let timeout = rule_int(&rules, ROW_TIMEOUT)?;
    let plugin = write_under(root, MANIFEST_REL, &render(&layout.name, &version))?;
    let hooks = write_under(root, HOOKS_REL, &render_hooks(&layout.name, timeout))?;
    let market = write_under(root, MARKETPLACE_REL, &render_marketplace(&layout.name))?;
    Ok(format!(
        "xtask gen-manifest: wrote {plugin}, {hooks} and {market} (name={} version={version} timeout={timeout}s)",
        layout.name
    ))
}

#[cfg(test)]
mod tests {
    use super::{
        generate, render, render_hooks, render_marketplace, rule_int, HOOKS_REL, MANIFEST_REL,
        MARKETPLACE_REL, ROW_TIMEOUT, RULES_REL,
    };
    use crate::check::{json_string_field, Layout};
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicU32, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    /// 同一 process 内での dir 名衝突を避ける連番（`cargo test` は thread 並走）。
    static SEQ: AtomicU32 = AtomicU32::new(0);

    /// fixture の NAME。**実在しない名**にする（生成器が字面を焼く変異は、この名が出力に
    /// 現れないことで落ちる）。
    const FIXTURE_NAME: &str = "fixturename";
    /// fixture の core version。
    const FIXTURE_VERSION: &str = "9.9.9";
    /// fixture の hook timeout（rules 行）。tracked の値と違えて「読んでいる」ことを測る。
    const FIXTURE_TIMEOUT: u64 = 7;

    /// repo の外に一意な tmp dir を作る（`tempfile` は足さない・憲法 A3）。
    /// `create_dir`（`_all` ではない）で既存 dir を衝突として検出し、連番を変えて取り直す。
    fn make_tmp_dir() -> PathBuf {
        let base = std::env::temp_dir();
        for _ in 0..8 {
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.subsec_nanos())
                .unwrap_or(0);
            let seq = SEQ.fetch_add(1, Ordering::Relaxed);
            let dir = base.join(format!("genmanifest-{}-{nanos}-{seq}", std::process::id()));
            if std::fs::create_dir(&dir).is_ok() {
                return dir;
            }
        }
        panic!("一意な tmp dir を 8 回で作れない");
    }

    /// `generate` が読む最小の workspace を tmp に組む（Cargo.toml・core crate・runner・rules）。
    fn write_fixture_root() -> PathBuf {
        let root = make_tmp_dir();
        let write = |rel: &str, body: &str| {
            let path = root.join(rel);
            std::fs::create_dir_all(path.parent().expect("親 dir")).expect("dir を作れる");
            std::fs::write(&path, body).expect("fixture を書ける");
        };
        write(
            "Cargo.toml",
            "[workspace]\nmembers = [\"crates/core\", \"crates/xtask\"]\n",
        );
        write(
            "crates/core/Cargo.toml",
            &format!("[package]\nname = \"core\"\nversion = \"{FIXTURE_VERSION}\"\n"),
        );
        write(
            "crates/core/src/name.rs",
            &format!("pub const NAME: &str = \"{FIXTURE_NAME}\";\n"),
        );
        write("crates/xtask/Cargo.toml", "[package]\nname = \"xtask\"\n");
        write(
            RULES_REL,
            &format!("[[rule]]\nid = \"{ROW_TIMEOUT}\"\nvalue = {FIXTURE_TIMEOUT}\n"),
        );
        root
    }

    /// tmp root の生成物を読む。
    fn read_generated(root: &Path, rel: &str) -> String {
        std::fs::read_to_string(root.join(rel)).unwrap_or_else(|err| panic!("{rel} を読める: {err}"))
    }

    /// `generate(root)` の**書く経路**: 3 つの manifest が実際に書かれ、render の返り値と byte
    /// 一致する（既存の 2 本は tracked 生成物との一致しか見ず、書く経路は無測定だった）。
    #[test]
    fn gen_manifest_writes_all_three_manifests_via_generate() {
        let root = write_fixture_root();
        for rel in [MANIFEST_REL, HOOKS_REL, MARKETPLACE_REL] {
            assert!(!root.join(rel).exists(), "生成前に {rel} は無い");
        }

        let report = generate(&root).expect("fixture の workspace から生成できる");
        // 後始末は assert より前に済ませる（赤い回に tmp を漏らさない・check.rs の作法と同じ）。
        let (plugin, hooks, market) = (
            read_generated(&root, MANIFEST_REL),
            read_generated(&root, HOOKS_REL),
            read_generated(&root, MARKETPLACE_REL),
        );
        std::fs::remove_dir_all(&root).ok();

        assert_eq!(plugin, render(FIXTURE_NAME, FIXTURE_VERSION), "plugin.json は render の bytes そのもの");
        assert_eq!(
            hooks,
            render_hooks(FIXTURE_NAME, FIXTURE_TIMEOUT),
            "hooks.json は render_hooks の bytes そのもの（timeout は fixture の rules 行）"
        );
        assert_eq!(
            market,
            render_marketplace(FIXTURE_NAME),
            "marketplace.json は render_marketplace の bytes そのもの"
        );
        assert!(
            report.contains(&format!("name={FIXTURE_NAME} version={FIXTURE_VERSION} timeout={FIXTURE_TIMEOUT}s")),
            "報告行は fixture の値を写す（tracked の値ではない）: {report}"
        );
        // 実在の名は tracked の workspace から読む（歯の source に字面を置かない・name-literal）。
        let real = Layout::discover(&workspace_root()).expect("workspace の配置を読める").name;
        assert!(
            !hooks.contains(&real),
            "生成器は実在の名（{real}）を焼いていない（fixture の名だけが出る）"
        );
    }

    /// 共有 `description(name)` が plugin.json と marketplace.json の**両方**へ届く: marketplace
    /// 自身の description（plugins の前・`claude plugin validate` が見る key）と plugin.json の
    /// description が同一 ∧ 非空 ∧ NAME を含む。A/B: description() の文言を変えると両面の期待が
    /// 同時に動く（片方だけ写して持つ形をこの歯は通さない）。
    #[test]
    fn gen_manifest_shared_description_reaches_both_manifests_via_generate() {
        let root = write_fixture_root();
        generate(&root).expect("fixture の workspace から生成できる");
        let plugin = read_generated(&root, MANIFEST_REL);
        let market = read_generated(&root, MARKETPLACE_REL);
        // 後始末は assert より前（赤い回に tmp を漏らさない）。
        std::fs::remove_dir_all(&root).ok();

        let in_plugin = json_string_field(&plugin, "description").expect("plugin.json に description");
        let market_head = market
            .split_once("\"plugins\"")
            .map(|(head, _)| head.to_owned())
            .expect("marketplace.json に plugins");
        let in_market = json_string_field(&market_head, "description")
            .expect("marketplace 自身（plugins の前）に description が在る");
        assert!(!in_plugin.is_empty(), "非空");
        assert_eq!(in_plugin, in_market, "2 つの manifest の description は同じ 1 箇所から出る");
        assert!(in_market.contains(FIXTURE_NAME), "description は NAME を含む: {in_market}");
        let (_, market_tail) = market.split_once("\"plugins\"").expect("plugins");
        assert_eq!(
            json_string_field(market_tail, "description").as_deref(),
            Some(in_market.as_str()),
            "plugins[0] の description も同じ 1 箇所から出る"
        );
    }

    /// workspace root（この crate の 2 つ上）。
    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
    }

    /// tracked な hooks.json が render の bytes と一致し、timeout が rules 行を写す。
    ///
    /// 生成物を手で直すと落ちる（手書き禁止の歯）。同じ入力から 2 回 render しても
    /// 同じ bytes であることも同時に測る（冪等）。
    #[test]
    fn gen_manifest_hooks_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let rules = std::fs::read_to_string(root.join(RULES_REL)).expect("rules manifest を読める");
        let timeout = rule_int(&rules, ROW_TIMEOUT).expect("hook.timeout_s を引ける");
        let rendered = render_hooks(&layout.name, timeout);
        let tracked = std::fs::read_to_string(root.join(HOOKS_REL)).expect("hooks.json を読める");

        assert_eq!(rendered, tracked, "tracked な hooks.json は生成物と同じ bytes である");
        assert_ne!(
            render_hooks(&layout.name, timeout + 1),
            rendered,
            "render は引数の timeout を実際に使う（値を焼いていない）"
        );
        assert!(
            tracked.contains(&format!("\"timeout\": {timeout}")),
            "timeout は rules 行 {ROW_TIMEOUT} の値（{timeout}）を写す"
        );
        assert_eq!(
            tracked.matches("\"type\": \"command\"").count(),
            3,
            "entry は SessionStart / PreToolUse / PermissionRequest の 3 つである"
        );
        // **数だけでなく名前で**測る。件数だけだと、event 名を取り違えた生成物
        // （同じ event を 3 回書く等）が同じ 3 で通る。
        for event in ["SessionStart", "PreToolUse", "PermissionRequest"] {
            assert_eq!(
                tracked.matches(&format!("\"{event}\": [")).count(),
                1,
                "{event} の entry がちょうど 1 つ在る"
            );
        }
    }

    /// tracked な marketplace.json が render の bytes と一致する（手書き禁止・冪等）。
    #[test]
    fn gen_manifest_marketplace_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let rendered = render_marketplace(&layout.name);
        let tracked =
            std::fs::read_to_string(root.join(MARKETPLACE_REL)).expect("marketplace.json を読める");

        assert_eq!(
            rendered, tracked,
            "tracked な marketplace.json は生成物と同じ bytes である"
        );
        assert_eq!(
            render_marketplace(&layout.name),
            rendered,
            "同じ入力からは同じ bytes（冪等）"
        );
        assert_ne!(
            render_marketplace("other-name"),
            rendered,
            "render は引数の name を実際に使う（字面を焼いていない）"
        );
        assert_eq!(
            tracked.matches("\"source\": \"./\"").count(),
            1,
            "source はちょうど 1 回（repo 自身を指す）: {tracked}"
        );
        let plugins = tracked
            .split_once("\"plugins\"")
            .map_or_else(String::new, |(_, tail)| tail.to_owned());
        assert_eq!(
            plugins
                .matches(&format!("\"name\": \"{}\"", layout.name))
                .count(),
            1,
            "plugins が名指す plugin はちょうど 1 件: {plugins}"
        );
        assert!(
            tracked.ends_with("}\n") && !tracked.ends_with("\n\n"),
            "末尾改行は 1 つ: {tracked:?}"
        );
    }
}
