//! `.claude-plugin/plugin.json` と `hooks/hooks.json` を NAME と rules 行から生成する。
//!
//! manifest を手書きしないのは、名前の字面が repo へ散るのを避けるためである
//! （器 SPEC §7）。生成は冪等で、同じ workspace からは同じ bytes が出る。
//! hook の timeout は数値を焼かず rules 行 `hook.timeout_s` から読む（憲法 C1 / C5）。

use crate::check::Layout;
use crate::toml_lite;
use std::fs;
use std::path::Path;

/// plugin manifest の相対 path。
pub const MANIFEST_REL: &str = ".claude-plugin/plugin.json";

/// hook manifest の相対 path。
pub const HOOKS_REL: &str = "hooks/hooks.json";

/// marketplace manifest の相対 path。
pub const MARKETPLACE_REL: &str = ".claude-plugin/marketplace.json";

/// 規則の値の正本の相対 path。
pub const RULES_REL: &str = "rules/manifest.toml";

/// hook 1 回の timeout（秒）を持つ rules 行。
pub const ROW_TIMEOUT: &str = "hook.timeout_s";

/// `PreToolUse` で見る tool の matcher。
const MATCHER: &str = "Edit|Write|MultiEdit|NotebookEdit";

/// `SessionStart` に紐づく subcommand。
const SUB_SESSION_START: &str = "session-start";

/// `PreToolUse` に紐づく subcommand。
const SUB_PRE_TOOL_USE: &str = "pre-tool-use";

/// `PermissionRequest` で見る tool の matcher（**`Bash` だけ**）。
///
/// 内蔵 guard の問いに答えるのは `Bash` の周に限る。広げると器が答える筋合いの無い
/// 承認まで機械が deny することになる。
const MATCHER_PERMISSION: &str = "Bash";

/// `PermissionRequest` に紐づく subcommand。
const SUB_PERMISSION_REQUEST: &str = "permission-request";

/// plugin の説明文。**2 つの manifest が同じ 1 箇所から出す**（写して持つと片方だけ動く）。
fn description(name: &str) -> String {
    format!("{name} plugin manifest (generated by cargo xtask gen-manifest)")
}

/// `name` / `version` / `description` の 3 key を持つ manifest 本文を組み立てる。
pub fn render(name: &str, version: &str) -> String {
    let description = description(name);
    format!("{{\n  \"name\": \"{name}\",\n  \"version\": \"{version}\",\n  \"description\": \"{description}\"\n}}\n")
}

/// `name` / `owner` / `plugins` の 3 key を持つ marketplace 本文を組み立てる。
///
/// **個人の handle・repo の URL・host の path・口座名を 1 文字も持たない**（本 repo は
/// PUBLIC・SRS CON2）。`owner.url` は任意の field なので**置かない**——置けるものを置くと、
/// 生成器が個人情報を repo へ流し込む常設の口になる。`source` を `./` に取るのは、この repo
/// 自身を directory marketplace として読ませるためで、絶対 path を書かずに済む形でもある。
pub fn render_marketplace(name: &str) -> String {
    let description = description(name);
    format!(
        "{{\n  \"name\": \"{name}\",\n  \"owner\": {{\n    \"name\": \"{name}\"\n  }},\n  \"plugins\": [\n    {{\n      \"name\": \"{name}\",\n      \"source\": \"./\",\n      \"description\": \"{description}\"\n    }}\n  ]\n}}\n"
    )
}

/// hook が起動するコマンドの字面。
///
/// `${<NAME_UPPER>_BIN:-<NAME>}` の展開は **Claude Code が hook を起動する shell**
/// が行う。器そのものは env を 1 つも読まない（憲法 C2.2・ADR-0004 §2.4）。
fn command(name: &str, sub: &str) -> String {
    format!("\\\"${{{}_BIN:-{name}}}\\\" hook {sub}", name.to_uppercase())
}

/// 1 event 分の entry を組む。
fn entry(event: &str, matcher: Option<&str>, name: &str, sub: &str, timeout: u64) -> String {
    let head = match matcher {
        Some(found) => format!("        \"matcher\": \"{found}\",\n"),
        None => String::new(),
    };
    format!(
        "    \"{event}\": [\n      {{\n{head}        \"hooks\": [\n          {{\n            \"type\": \"command\",\n            \"command\": \"{}\",\n            \"timeout\": {timeout}\n          }}\n        ]\n      }}\n    ]",
        command(name, sub)
    )
}

/// hooks.json 本文を組み立てる（entry は 3 つ・timeout は rules 行を写す）。
pub fn render_hooks(name: &str, timeout: u64) -> String {
    let entries = [
        entry("SessionStart", None, name, SUB_SESSION_START, timeout),
        entry("PreToolUse", Some(MATCHER), name, SUB_PRE_TOOL_USE, timeout),
        entry(
            "PermissionRequest",
            Some(MATCHER_PERMISSION),
            name,
            SUB_PERMISSION_REQUEST,
            timeout,
        ),
    ];
    format!("{{\n  \"hooks\": {{\n{}\n  }}\n}}\n", entries.join(",\n"))
}

/// rules manifest から `id` の行の `value` を整数で引く。
///
/// `[[rule]]` は array-of-tables なので、section 行で block を切り替えながら
/// 「いま読んでいる block の id」を追う（file 全体の行 grep はしない）。
pub fn rule_int(text: &str, id: &str) -> Result<u64, String> {
    let mut current: Option<String> = None;
    for line in text.lines() {
        if toml_lite::section_header(line).is_some() {
            current = None;
            continue;
        }
        let Some((key, raw)) = toml_lite::key_value(line) else {
            continue;
        };
        if key == "id" {
            current = toml_lite::quoted(raw);
        }
        if key == "value" && current.as_deref() == Some(id) {
            return raw
                .parse::<u64>()
                .map_err(|err| format!("{id} の value が整数でない（{raw}・{err}）"));
        }
    }
    Err(format!("{id} が {RULES_REL} に無い"))
}

/// `root` 配下の 1 file を親 dir ごと書き出す。
fn write_under(root: &Path, rel: &str, body: &str) -> Result<String, String> {
    let path = root.join(rel);
    let dir = path
        .parent()
        .ok_or_else(|| format!("{} の親 dir が無い", path.display()))?;
    fs::create_dir_all(dir).map_err(|err| format!("{} を作れない: {err}", dir.display()))?;
    fs::write(&path, body).map_err(|err| format!("{} を書けない: {err}", path.display()))?;
    Ok(path.display().to_string())
}

/// workspace `root` の plugin manifest と hook manifest を生成して書き出し、報告行を返す。
pub fn generate(root: &Path) -> Result<String, String> {
    let layout = Layout::discover(root)?;
    let version = layout.core_version()?;
    let rules = fs::read_to_string(root.join(RULES_REL))
        .map_err(|err| format!("{RULES_REL} を読めない: {err}"))?;
    let timeout = rule_int(&rules, ROW_TIMEOUT)?;
    let plugin = write_under(root, MANIFEST_REL, &render(&layout.name, &version))?;
    let hooks = write_under(root, HOOKS_REL, &render_hooks(&layout.name, timeout))?;
    let market = write_under(root, MARKETPLACE_REL, &render_marketplace(&layout.name))?;
    Ok(format!(
        "xtask gen-manifest: wrote {plugin}, {hooks} and {market} (name={} version={version} timeout={timeout}s)",
        layout.name
    ))
}

#[cfg(test)]
mod tests {
    use super::{render_hooks, render_marketplace, rule_int, HOOKS_REL, MARKETPLACE_REL, ROW_TIMEOUT, RULES_REL};
    use crate::check::Layout;
    use std::path::PathBuf;

    /// workspace root（この crate の 2 つ上）。
    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
    }

    /// tracked な hooks.json が render の bytes と一致し、timeout が rules 行を写す。
    ///
    /// 生成物を手で直すと落ちる（手書き禁止の歯）。同じ入力から 2 回 render しても
    /// 同じ bytes であることも同時に測る（冪等）。
    #[test]
    fn gen_manifest_hooks_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let rules = std::fs::read_to_string(root.join(RULES_REL)).expect("rules manifest を読める");
        let timeout = rule_int(&rules, ROW_TIMEOUT).expect("hook.timeout_s を引ける");
        let rendered = render_hooks(&layout.name, timeout);
        let tracked = std::fs::read_to_string(root.join(HOOKS_REL)).expect("hooks.json を読める");

        assert_eq!(rendered, tracked, "tracked な hooks.json は生成物と同じ bytes である");
        assert_ne!(
            render_hooks(&layout.name, timeout + 1),
            rendered,
            "render は引数の timeout を実際に使う（値を焼いていない）"
        );
        assert!(
            tracked.contains(&format!("\"timeout\": {timeout}")),
            "timeout は rules 行 {ROW_TIMEOUT} の値（{timeout}）を写す"
        );
        assert_eq!(
            tracked.matches("\"type\": \"command\"").count(),
            3,
            "entry は SessionStart / PreToolUse / PermissionRequest の 3 つである"
        );
        // **数だけでなく名前で**測る。件数だけだと、event 名を取り違えた生成物
        // （同じ event を 3 回書く等）が同じ 3 で通る。
        for event in ["SessionStart", "PreToolUse", "PermissionRequest"] {
            assert_eq!(
                tracked.matches(&format!("\"{event}\": [")).count(),
                1,
                "{event} の entry がちょうど 1 つ在る"
            );
        }
    }

    /// tracked な marketplace.json が render の bytes と一致する（手書き禁止・冪等）。
    #[test]
    fn gen_manifest_marketplace_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let rendered = render_marketplace(&layout.name);
        let tracked =
            std::fs::read_to_string(root.join(MARKETPLACE_REL)).expect("marketplace.json を読める");

        assert_eq!(
            rendered, tracked,
            "tracked な marketplace.json は生成物と同じ bytes である"
        );
        assert_eq!(
            render_marketplace(&layout.name),
            rendered,
            "同じ入力からは同じ bytes（冪等）"
        );
        assert_ne!(
            render_marketplace("other-name"),
            rendered,
            "render は引数の name を実際に使う（字面を焼いていない）"
        );
        assert_eq!(
            tracked.matches("\"source\": \"./\"").count(),
            1,
            "source はちょうど 1 回（repo 自身を指す）: {tracked}"
        );
        let plugins = tracked
            .split_once("\"plugins\"")
            .map_or_else(String::new, |(_, tail)| tail.to_owned());
        assert_eq!(
            plugins
                .matches(&format!("\"name\": \"{}\"", layout.name))
                .count(),
            1,
            "plugins が名指す plugin はちょうど 1 件: {plugins}"
        );
        assert!(
            tracked.ends_with("}\n") && !tracked.ends_with("\n\n"),
            "末尾改行は 1 つ: {tracked:?}"
        );
    }
}
